############# English navigation ##############

[[main]]
name = "Products"
url = "project/"
weight = 1
hasChildren = true

  [[main]]
  parent = "Products"
  name = "Scignabot"
  url = "blog/scignabot_proyecto/"
  weight = 1

  [[main]]
  parent = "Products"
  name = "Signalino"
  url = "blog/recording-signals-signalino/"
  weight = 2

  [[main]]
  parent = "Products"
  name = "Memboost"
  url = "blog/enhancing-memory-memboost/"
  weight = 3

[[main]]
name = "Services"
url = "/index.html#miservicio"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "About"
url = "about/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2


[[footer]]
name = "About"
url = "about/"
weight = 3

[[footer]]
name = "Projects"
url = "/categories/projects/"
weight = 4

[[footer]]
name = "Contact"
url = "contact/"
weight = 6
