############# English navigation ##############

[[main]]
name = "Productos"
url = "project/"
weight = 1
hasChildren = true

  [[main]]
  parent = "Productos"
  name = "Scignabot"
  url = "blog/scignabot_proyecto/"
  weight = 1

  [[main]]
  parent = "Productos"
  name = "Signalino"
  url = "blog/recording-signals-signalino/"
  weight = 3

  [[main]]
  parent = "Productos"
  name = "Memboost"
  url = "blog/enhancing-memory-memboost/"
  weight = 2

  [[main]]
  parent = "Productos"
  name = "Signalino 8"
  url = "http://www.signalino.org/signalino-8"
  weight = 4
  
  [[main]]
  parent = "Productos"
  name = "Signalino Due"
  url = "http://www.signalino.org/signalino-due"
  weight = 5

[[main]]
name = "Servicios"
url = "/index.html#miservicio"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "Nosotros"
url = "about/"
weight = 5

[[main]]
name = "Tienda"
url = "http://wp.signalino.org/shop/"
weight = 6

[[main]]
name = "Contacto"
url = "contact/"
weight = 7


# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2


[[footer]]
name = "About"
url = "about/"
weight = 3

[[footer]]
name = "Project"
url = "project/"
weight = 4

[[footer]]
name = "Service"
url = "service/"
weight = 5


[[footer]]
name = "Contacta"
url = "contact/"
weight = 6
