#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo_scignals.jpg"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "230px"
# logo text will only show when logo is missing.
logo_text = "Scignals"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Scignals"
image = "images/logo_scignals.png" # this image will be used as fallback if a page has no image of its own
# Whether to display text descriptors (like "E-mail: ", "Phone: ") before the address block elements
address_descriptors = false
# contact info
phone = "0124857985320"
email = "info@scignals.com"
location = """
**Scignals**  [ILSB: Investigación y Lectura de Señales Biomédicas].

Parque Científico y Empresarial - Universidad Miguel Hernández<br/>
Edificio Quorum 3<br/>
Avda. de la Universidad s/n<br/>
03202, Elche (Spain)

"""
# copyright
copyright = "<img src=\"/images/logo-eu-02-en.svg\" width=\"50\" height=\"60\" > <img src=\"/images/mini_ivace.png\" height=\"60\" > Project co-financed by FEDER Programme of Comunitat Valenciana 2014-2020"
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
# recaptch v3 site key
recaptcha_site_key = "xxx-xxxxxxxxxxxxxxxxxxxxxxxx"

[contact.form]
enable = true
# Whether to use [Netlify Forms](https://docs.netlify.com/forms/setup/)
use_netlify = false
# Whether to use recaptch v3 in form
use_recaptcha = false
# Form action
## Fill in your Form ID URL for Formspree.io, e.g. `https://formspree.io/f/{form_id}`
## Ignored if `use_netlify = true` (custom [success page](https://docs.netlify.com/forms/setup/#success-messages) is already included) 
action = "https://forms.un-static.com/forms/cb0b53fcbf70a276cc44e7d6cd94b19a223f9ff2"
# Image on custom success page `/message_sent.html`
success_image = "images/paper-plane.svg"

legal_formulario="""
**Responsable del tratamiento**: Los datos tratados en el presente formulario, serán tratados por la empresa INVESTIGACION Y LECTURA DE SEÑALES BIOMEDICAS, S.L. con CIF  y domicilio en  como Responsable del Tratamiento de los datos.

**Finalidad**: Le queremos informar que la finalidad de los datos recogidos es la gestión de usuarios de la página web, así como la gestión de comunicación electrónica.

**Legitimación**: consentimiento otorgado marcando la correspondiente casilla de verificación. Sus datos personales serán tratados en base a nuestra política de privacidad.

**Negativa a otorgar el consentimiento**: El hecho de que no introduzca los datos que aparecen marcados como obligatorios en el formulario tendrá como consecuencia la no atención de su solicitud.

**Destinatarios**: Sus datos no serán cedidos a ninguna empresa, salvo obligación legal.

**Derechos**: Puede acceder, rectificar y suprimir sus datos, solicitar la portabilidad de estos, así como su limitación u oposición a su tratamiento, tiene derecho a no ser objeto de decisiones automatizadas, así como a obtener información clara y transparente sobre el tratamiento de sus datos, tal como se explica en la información adicional.

**Derecho a presentar una reclamación ante la Autoridad de Control (AEPD)**: Desde INVESTIGACION Y LECTURA DE SEÑALES BIOMEDICAS, S.L. ponemos el máximo empeño para cumplir con la normativa de protección de datos dado que es el activo más valioso para nosotros.

**Información adicional**: Puede consultar la información adicional y detallada sobre protección de Datos en nuestra página web.
"""
# Preloader
[preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "get a quote"
link = "contact"


# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = "" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = "" # your username

# site verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code

# google map
[gmap]
enable = true
gmap_api = "AIzaSyDw5ItcP5keSOpkBNsImEUf0WMovtxWzn8"
map_latitude = "38.2791373"
map_longitude = "-0.6915287"
map_marker = "images/marker.png"

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
# available widget : categories,tags,recent-post

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook"  # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.facebook.com/Signalino-196304170821156/"

[[social]]
title = "twitter"
icon = "fab fa-twitter"  # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://twitter.com/signalino2"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://goo.gl/xxoTVmj3"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"
