
[contact.form]

legal_formulario="""
**Responsable del tratamiento**: Los datos tratados en el presente formulario, serán tratados por la empresa INVESTIGACION Y LECTURA DE SEÑALES BIOMEDICAS, S.L. con CIF  y domicilio en  como Responsable del Tratamiento de los datos.

**Finalidad**: Le queremos informar que la finalidad de los datos recogidos es la gestión de usuarios de la página web, así como la gestión de comunicación electrónica.

**Legitimación**: consentimiento otorgado marcando la correspondiente casilla de verificación. Sus datos personales serán tratados en base a nuestra política de privacidad.

**Negativa a otorgar el consentimiento**: El hecho de que no introduzca los datos que aparecen marcados como obligatorios en el formulario tendrá como consecuencia la no atención de su solicitud.

**Destinatarios**: Sus datos no serán cedidos a ninguna empresa, salvo obligación legal.

**Derechos**: Puede acceder, rectificar y suprimir sus datos, solicitar la portabilidad de estos, así como su limitación u oposición a su tratamiento, tiene derecho a no ser objeto de decisiones automatizadas, así como a obtener información clara y transparente sobre el tratamiento de sus datos, tal como se explica en la información adicional.

**Derecho a presentar una reclamación ante la Autoridad de Control (AEPD)**: Desde INVESTIGACION Y LECTURA DE SEÑALES BIOMEDICAS, S.L. ponemos el máximo empeño para cumplir con la normativa de protección de datos dado que es el activo más valioso para nosotros.

**Información adicional**: Puede consultar la información adicional y detallada sobre protección de Datos en nuestra página web.
"""
